analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    todo: ignore
    invalid_annotation_target: ignore
    unused_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
    override_on_non_overriding_member: ignore
    annotate_overrides: ignore
    avoid_print: ignore
    prefer_const_constructors: ignore
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    
linter:
  rules:
    # Disable all strict rules for hackathon
    avoid_print: false
    prefer_single_quotes: false
    always_use_package_imports: false
